### ISSUE TITLE
Dockerfile explanation

### ISSUE THREAD

**Issue by azro352** [burakince/mlflow#113]
Hi, 

I understand the purpose of the project to build a docker with not only mlflow but also sql, s3, ... dependencies, but I'm unsure about 
why the [Dockerfile](https://github.com/burakince/mlflow/blob/main/Dockerfile) is like it is

I understand the multi-stage docker purpose, but here why can't we just install the dependencies like the following, I don't understnad the lib installation part not the `Install build-essential to compile extensions` comment ? 

```dockerfile
FROM python:3.9.16-slim

WORKDIR /mlflow/

COPY pyproject.toml poetry.toml poetry.lock /mlflow/

RUN python -m pip install --upgrade pip
RUN pip install poetry wheel &&  poetry install --no-root --no-dev

ENV PATH=/mlflow/.venv/bin:$PATH
ENV PYTHONUNBUFFERED 1

CMD mlflow server --backend-store-uri sqlite:///:memory --default-artifact-root ./mlruns --host=0.0.0.0 --port=5000
```

Thanks

**Comment by burakince** [comment]
Hi @azro352,

Apologies for the delayed response. The foundation layer includes additional packages because I cross-compile the Docker image for both amd64 and arm64 architectures. While some of these dependencies are specifically required for arm64 builds, others are likely still necessary for amd64 builds as well.

That said, these dependencies are only needed during the build process and are not included in the final Docker image. If you inspect the layers of the resulting image, you’ll find that these additional packages are excluded.

I hope this explanation helps clarify things.

Best regards,
Burak

**Comment by burakince** [comment]
I close the issue. Please feel free to reopen it if you need further explanation.
